[build]
  publish = "/"  # Specify the directory where your FastAPI application resides
  functions = "/"  # Specify the directory where your serverless functions will be stored
  command = "pip install -r requirements.txt -t . && cd path/to/your/fastapi/app && uvicorn main:app --host 0.0.0.0 --port $PORT"  # Install dependencies, then start the FastAPI app with Uvicorn

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
